project_id = "pvmdbqbhzmofbqqelyfh"

[functions.create-migrated-users]
verify_jwt = false

[functions.approve-email-change]
verify_jwt = true

[functions.reset-user-password]
verify_jwt = true

[functions.admin-user-operations]
verify_jwt = true
